# Generated by Django 5.2.9 on 2025-12-23 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('code', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Code utilisateur')),
                ('slug', models.SlugField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Adresse e-mail')),
                ('civilite', models.CharField(choices=[('', '-Choisir une civilité-'), ('M', 'Monsieur'), ('Mme', 'Madame'), ('Entr', 'Entreprise')], default='', max_length=4, verbose_name='Civilité')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=250, verbose_name="Complément d'adresse")),
                ('cp', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Le code postal doit contenir 5 chiffres')], verbose_name='Code postal')),
                ('ville', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Le nom de la ville contient des caractères non autorisés.', regex="^[a-zA-Zà-ÿÀ-ß\\s\\(\\)'-]+$")], verbose_name='Ville')),
                ('tel', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Le numéro de téléphone doit contenir 10 chiffres')], verbose_name='Téléphone')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('tentative', models.IntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('blocage', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de blocage')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
